version: '3.3'

networks:
  dock_net:
networks:
  dock_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16


services:
  db_master:
    image: mysql:latest
    container_name: db_master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./master/data:/var/lib/mysql
      - ./master/config/:/etc/mysql/conf.d
    ports:
      - 13306:3306
    networks:
      dock_net:
        ipv4_address: 172.16.0.10

  db_slave:
    image: mysql:latest
    container_name: db_slave
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./slave/data:/var/lib/mysql
      - ./slave/config/:/et/mysql/conf.d
    ports:
      - 13307:3306
    networks:
      dock_net:
        ipv4_address: 172.16.0.11
    depends_on:
      - db_master


# master
# CREATE USER 'repluser'@'%' IDENTIFIED BY 'replpw';
# GRANT REPLICATION SLAVE ON *.* TO 'repluser'@'%';
# CREATE TABLE repltable ( no INT(8), PRIMARY KEY (no) );
# DESC reptable;
# mysqldump -u root -p repldb > dump.sql 

# docker -> local
# docker cp {container_name}:/test.txt /test/
# docker cp test.txt {container_name}:/test

# slave
# CREATE DATABASE repldb;
# mysql -u root -p repldb < dump.sql

# slave 서버에서 master 연동하기
# SHOW MASTER status\G;
# CHANGE MASTER TO MASTER_HOST='mysql-master', MASTER_USER='repluser', MASTER_PASSWORD='replpw', MASTER_LOG_FILE='mysql-bin.000003', MASTER_LOG_POS=1111;
# SHOW SLAVE status\G;

    

  